### ISSUE TITLE
Export only labeled files

### ISSUE THREAD

**Issue by uPagge** [zoni/obsidian-export#161] opened 2023-09-03 10:38 UTC
I would like to be able to export only explicitly selected files.

For example, the choice could be made using the export parameter: true
 
```file.md
---
alias: test
export: true
---
\# h1 
Content
```

**Comment by epsilonhalbe** [comment] 2023-09-17 15:01
duplicate of issue #66 
fixed by PR #163

**Comment by epsilonhalbe** [comment] 2023-12-28 16:48
@zoni @uPagge i think this can be closed

**Comment by zoni** [comment] 2023-12-28 21:13
Indeed!

**Closed by zoni** 2023-12-28 21:13 UTC
