### ISSUE TITLE
Broken escaping of square brackets in math

### ISSUE THREAD

**Issue by mattchrlw** [zoni/obsidian-export#14] opened 2021-03-03 03:55 UTC
Hi there, this program has been immensely useful for getting my Obsidian docs into `LaTeX`, so thank you 🙏.

I've noticed that certain blocks of mathematics (in `LaTeX`) are handled incorrectly, breaking the math environments. For example, if you include a left-bracket in a `LaTeX` environment (such as `$[0, 2\pi)$`), after `obsidian-export` is run it will be converted to `$\[0, 2\pi)$` (which is invalid).

I assume this is something to do with `[[Wikilink]]` parsing, but I don't know enough Rust to investigate 😅 I think a possible solution would be to ignore any parsing or modification inside math blocks and instead treat them verbatim.

![image](https://user-images.githubusercontent.com/36957422/109750418-24086c80-7c28-11eb-8415-65fff939075e.png)

**Comment by zoni** [comment] 2021-03-04 18:31
> I assume this is something to do with [[Wikilink]] parsing, but I don't know enough Rust to investigate sweat_smile I think a possible solution would be to ignore any parsing or modification inside math blocks and instead treat them verbatim.

It's unfortunately a little bit more complex than that.

I use [pulldown-cmark](https://crates.io/crates/pulldown-cmark) to parse the Markdown document, which for this input:

```markdown
# Heading 1

## Heading 2

### Heading 3

> Single line quote.

---

> Multi-paragraph quote, line 1.
>
> Multi-paragraph quote, line 2.
> Multi-paragraph quote, line 3.
```

Generates these events:

```
Start(Heading(1))
Text(Borrowed("Heading 1"))
End(Heading(1))
Start(Heading(2))
Text(Borrowed("Heading 2"))
End(Heading(2))
Start(Heading(3))
Text(Borrowed("Heading 3"))
End(Heading(3))
Start(BlockQuote)
Start(Paragraph)
Text(Borrowed("Single line quote."))
End(Paragraph)
End(BlockQuote)
Rule
Start(BlockQuote)
Start(Paragraph)
Text(Borrowed("Multi-paragraph quote, line 1."))
End(Paragraph)
Start(Paragraph)
Text(Borrowed("Multi-paragraph quote, line 2."))
SoftBreak
Text(Borrowed("Multi-paragraph quote, line 3."))
End(Paragraph)
End(BlockQuote)
```

Then I do some logic to replace `[[WikiLinks]]` correctly and feed the above stream of events to [pulldown-cmark-to-cmark](https://crates.io/crates/pulldown-cmark-to-cmark) to convert this into Markdown text again.

There are some complexities here:

1. pulldown-cmark doesn't understand LaTeX math blocks, so we're treating this as regular pieces of text.
2. pulldown-cmark-to-cmark escapes any lone `[` character (so it becomes `\[`) as part of its text encoding, because if it doesn't escape this, it denotes the start of a link.

What pulldown-cmark-to-cmark is doing is technically correct, though I think if it simply didn't do this, you'd get the correct behavior you're expecting.

We might be able to convince the pulldown-cmark-to-cmark authors to make this behavior configurable.
I don't feel like doing this right now, but I'll file an issue on their repo and explain this use-case to see how they feel about that.

**Comment by mattchrlw** [comment] 2021-03-09 23:23
Ahh, that's a shame. For what it's worth, this problem can easily be remedied after the fact with some search-and-replace, as the problematic character sequences are quite predictable (`$\[ -> $[` etc.) But I can see how this can become quite complex, even if it is made configurable...

Thanks for investigating anyway.

**Comment by Masstronaut** [comment] 2022-05-03 02:56
I've just encountered a similar issue with escaped `%` characters (`\%`) in math sequences. In my case the reverse is happening - `\%` in my source notes becomes `%` in the output from `obsidian-export`. This is problematic as the `%` character is a comment in TeX syntax, so in an inline math block like `$5\%$` that gets output as `$5%$` the TeX parser sees `$5` followed by the `%` token which marks the rest of the line - `$` - as a comment. This breaks the syntax as the parser sees no closing `$`.

Is this likely caused by the same upstream dependency, or do you think something else could be at play here?

**Comment by k4ds3** [comment] 2022-10-16 21:13
```
> [!NOTE] Test
> Test
```

also gets exported as 

```
 >
 > \[!NOTE\] Test
 > Test
```

which breaks the callouts/admonitions when further processing the markdown in e.g. mkdocs :(

**Comment by zoni** [comment] 2022-11-21 10:57
There's now a PR on pulldown-cmark to parse math blocks: https://github.com/raphlinus/pulldown-cmark/pull/622 

If and when that is accepted and merged, and rendering support is also added to [pulldown-cmark-to-cmark](https://github.com/Byron/pulldown-cmark-to-cmark/) (which should be straightforward to implement) then the math rendering/escaping problems in this issue will be fixed.

**Comment by maneesh29s** [comment] 2024-06-01 09:54
Today I faced same issue while exporting latex, where my `[` and `*` were being replaced with `\[` and `\*` respectively.

Today I saw that there have been some merges in pulldown-cmark, particularly [#734](https://github.com/pulldown-cmark/pulldown-cmark/pull/734) which closed the issue [#622](https://github.com/pulldown-cmark/pulldown-cmark/pull/622) mentioned by zoni above.

Can this issue be fixed now?

**Comment by maneesh29s** [comment] 2024-06-02 06:49
After a little more investigation, here's my findings:

## pulldown-cmark

The math mode has been integrated in the latest [v0.11.0](https://github.com/pulldown-cmark/pulldown-cmark/releases/tag/v0.11.0) release of `pulldown-cmark`. 
But there have been many breaking changes since v0.9.3 (current dependency of `obsidian-export`), for example in Event and Tag enums. 

## pulldown-cmark-to-cmark

The latest version of `pulldown-cmark-to-cmark` is v13.0.0, which still depends on `pulldown-cmark` 0.10.0. 
That means `pulldown-cmark-to-cmark` does not support math mode yet.

**Comment by maneesh29s** [comment] 2024-07-17 17:41
Update:

pulldown-cmark-to-cmark has been updated to [v15.0.1](https://github.com/Byron/pulldown-cmark-to-cmark/releases/tag/v15.0.1) which has added support for the math mode in `pulldown-cmark`

The renovate bot has tried to update these dependencies (see #259  and #252), but both have failed test cases.

**Comment by zoni** [comment] 2024-07-18 13:27
pulldown-cmark 0.10 introduced quite a few breaking changes. It's not terribly difficult to get those upgrades done, it's just a chore I haven't had the energy/motivation for yet :smile: It's certainly on my list to action in the future though

**Comment by maneesh29s** [comment] 2024-08-06 17:56
Thank you for the efforts that you are making to close this issue. 
This will reduce a lot of my hassle of checking notes post-conversion.

**Closed** 2024-08-10 08:55 UTC

**Comment by zoni** [comment] 2024-08-10 09:01
Issues with broken math should be fixed with the upcoming release :tada: 

(Callouts/admonitions and other Obsidian-specific constructs that aren't actual CommonMark may continue to give problems though. Unfortunately there's not much I can do about that without completely forking pulldown-cmark to add Obsidian syntax to its grammar, which is not something I have the time to support for now)

**Comment by maneesh29s** [comment] 2024-11-16 13:24
Hii @zoni , thanks for fixing this.
Do you have any plans about when the next release will happen ?

**Comment by zoni** [comment] 2024-11-23 14:44
@maneesh29s apologies, I'd planned to combine a few other small updates into the upcoming release, but the life got in the way. I've cut a new release so you won't have to wait any longer, v24.11.0 is being built and published now.
